// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Startup(arg1) {
  return window['go']['utils']['Utils']['Startup'](arg1);
}

export function WatchClipboard() {
  return window['go']['utils']['Utils']['WatchClipboard']();
}
