// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function AddClipBoardItem(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function DeleteClipBoardItem(arg1:number):Promise<void>;

export function DeleteClipBoardItemById(arg1:number):Promise<void>;

export function GetAllClipBoardItems():Promise<Array<store.ClipboardItemDbRow>>;

export function GetClipBoardItemById(arg1:number):Promise<store.ClipboardItemDbRow>;

export function GetClipboardContent():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function UpdateClipBoardItemById(arg1:number,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;
