// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClipBoardItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddClipBoardItem'](arg1, arg2, arg3);
}

export function DeleteClipBoardItem(arg1) {
  return window['go']['main']['App']['DeleteClipBoardItem'](arg1);
}

export function DeleteClipBoardItemById(arg1) {
  return window['go']['main']['App']['DeleteClipBoardItemById'](arg1);
}

export function GetAllClipBoardItems() {
  return window['go']['main']['App']['GetAllClipBoardItems']();
}

export function GetClipBoardItemById(arg1) {
  return window['go']['main']['App']['GetClipBoardItemById'](arg1);
}

export function GetClipboardContent() {
  return window['go']['main']['App']['GetClipboardContent']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateClipBoardItemById(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateClipBoardItemById'](arg1, arg2, arg3, arg4);
}
